version: "3.3"
services:
  gateway:
    image: 192.168.56.1:5000/gateway
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - 5050:5050
    network_mode: "host"