apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database-statefulset
spec:
  selector:
    matchLabels:
      layer: database
  serviceName: "database"
  template:
    metadata:
      labels:
        layer: database
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: database
        image: 192.168.56.1:5000/database
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mydb
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
  volumeClaimTemplates:
  - metadata:
      name: mydb
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 0.5G