apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      layer: gateway
  template:
    metadata:
      name: gateway
      labels:
        layer: gateway
    spec:
      containers:
      - name: gateway
        image: 192.168.56.1:5000/gateway
        ports:
        - containerPort: 5050